[book]
authors = ["Ankitects Pty Ltd and contributors"]
language = "en"
multilingual = false
src = "src"
title = "Anki Betas"

[build]
create-missing = true

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]

[output.html]
no-section-label = true
git-repository-url = "https://github.com/ankitects/anki-betas/"

[output.linkcheck]
optional = true
warning-policy = "warn"
follow-web-links = true

[output.html.redirect]
"/index.html" = "https://docs.ankiweb.net/releases/betas/intro"
"/anki2.1.44.html" = "https://docs.ankiweb.net/releases/betas/anki2.1.44" 
"/github.html" = "https://docs.ankiweb.net/releases/betas/github" 
"/older.html" = "https://docs.ankiweb.net/releases/betas/older" 
"/anki2.1.62.html" = "https://docs.ankiweb.net/releases/betas/anki2.1.62" 
"/anki2.1.47.html" = "https://docs.ankiweb.net/releases/betas/anki2.1.47" 
"/2021-scheduler.html" = "https://docs.ankiweb.net/releases/betas/2021-scheduler" 
"/anki23.10.html" = "https://docs.ankiweb.net/releases/betas/anki23.10" 
"/anki2.1.53.html" = "https://docs.ankiweb.net/releases/betas/anki2.1.53" 
"/anki2.1.50.html" = "https://docs.ankiweb.net/releases/betas/anki2.1.50" 
"/anki2.1.57.html" = "https://docs.ankiweb.net/releases/betas/anki2.1.57" 
"/anki2.1.41.html" = "https://docs.ankiweb.net/releases/betas/anki2.1.41" 
"/anki2.1.66.html" = "https://docs.ankiweb.net/releases/betas/anki2.1.66" 
"/anki2.1.48.html" = "https://docs.ankiweb.net/releases/betas/anki2.1.48" 
"/intro.html" = "https://docs.ankiweb.net/releases/betas/intro" 
"/anki2.1.51.html" = "https://docs.ankiweb.net/releases/betas/anki2.1.51" 
"/anki2.1.43.html" = "https://docs.ankiweb.net/releases/betas/anki2.1.43" 
"/anki2.1.56.html" = "https://docs.ankiweb.net/releases/betas/anki2.1.56" 
"/anki2.1.54.html" = "https://docs.ankiweb.net/releases/betas/anki2.1.54" 
"/anki2.1.61.html" = "https://docs.ankiweb.net/releases/betas/anki2.1.61" 
"/anki2.1.45.html" = "https://docs.ankiweb.net/releases/betas/anki2.1.45" 
"/anki2.1.52.html" = "https://docs.ankiweb.net/releases/betas/anki2.1.52" 
"/anki2.1.55.html" = "https://docs.ankiweb.net/releases/betas/anki2.1.55" 

