[book]
authors = ["Ankitects Pty Ltd and contributors"]
language = "en"
multilingual = false
src = "src"
title = "Anki Betas"

[build]
create-missing = true

[output.html]
no-section-label = true
git-repository-url = "https://github.com/ankitects/anki-betas/"
